// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoExtended.Web.Data;

#nullable disable

namespace TodoExtended.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402164135_AddTaskReminderAndRecurring")]
    partial class AddTaskReminderAndRecurring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CachedTaskTags", b =>
                {
                    b.Property<string>("TagName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagUserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("TagName", "TagUserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TagUserId", "TagName");

                    b.ToTable("CachedTaskTags");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash");

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name", "UserId");

                    b.HasIndex("UserId", "IsPinned");

                    b.ToTable("CachedTags");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasReminder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Importance")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("ListId", "IsDeleted");

                    b.HasIndex("UserId", "IsDeleted", "DueDate");

                    b.ToTable("CachedTasks");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTaskList", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaToken")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSyncUtc");

                    b.HasIndex("UserId", "IsSynced");

                    b.ToTable("CachedTaskLists");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.DistributedCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SlidingExpirationInSeconds")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.HasIndex("AbsoluteExpiration");

                    b.HasIndex("LastAccessed");

                    b.ToTable("DistributedCacheEntries");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.SyncMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.TaskTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DueDateToday")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskListId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskListName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedCacheData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("CachedTaskTags", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.CachedTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoExtended.Web.Data.CachedTag", null)
                        .WithMany()
                        .HasForeignKey("TagName", "TagUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoExtended.Web.Data.ApiKey", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTag", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTask", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.CachedTaskList", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.TaskTemplate", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.UserToken", b =>
                {
                    b.HasOne("TodoExtended.Web.Data.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("TodoExtended.Web.Data.UserToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.CachedTaskList", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TodoExtended.Web.Data.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
